# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c80dc2ff5d74bb626c5248b8855d0576500b3ab7b03b650509a4e19af459c4541d0110dc43a1be526cec366c46be6b964b316044bb3f2bdd911515eeb21411e

test:
  secret_key_base: 7b92ae5e17fac46b76cb4b0aa9b05ae91c45fdbaf4484026b7631c9be198114bc3c2ee4a0591908b8094bb8441968398361c2a18abefd7bef7982d0cb51415e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
